---
title: "Song Analysis"
author: "Scott Onestak"
date: "9/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#READ IN PACKAGES
```{r packages}
if (!require("dplyr")) install.packages("dplyr",dependencies = T)

library(dplyr)
```

#READ IN SONG DATASET
```{r read data}
songs_raw = read.csv('sonestak.csv',header=F,stringsAsFactors = F)
colnames(songs_raw) = c('Artist','Album','Track','Timestamp')
```

#CLEANING
```{r cleaning}
songs = songs_raw
songs$Track[songs$Track =="starstrukk (feat. katyperry)"] = "Starstrukk (feat. Katy Perry)"
songs$Track[songs$Track == "The Chipmunk Song (Christmas Don't Be Late) - Remastered" | 
                songs$Track == "The Chipmunk Song (Christmas Don't Be Late) - Remastered 1999" ] = "The Chipmunk Song (Christmas Don't Be Late)"
songs$Track[songs$Track == "Be Our Guest - From Beauty and the Beast/Soundtrack" | 
                songs$Track == "Beauty and the Beast - From Beauty and the Beast/Soundtrack Version" ] = "Be Our Guest - From Beauty and the Beast"
songs$Track[songs$Track == "Cups (Pitch Perfect’s “When I’m Gone”) - Pop Version" |
                songs$Track == "Cups (Pitch Perfect’s “When I’m Gone”)"] = "Cups (Pitch Perfect's 'When I'm Gone')"
songs$Track[songs$Track == "You’ll Never Know"] = "You'll Never Know"
songs$Track[songs$Track == "I Could Be The One (Avicii Vs. Nicky Romero) - Nicktim / Radio Edit" |
                songs$Track == "I Could Be The One [Avicii vs Nicky Romero] - Nicktim - Radio Edit" |
                songs$Track == "I Could Be The One [Avicii vs Nicky Romero] - Nicktim / Radio Edit"] =
  "I Could Be The One (Avicii Vs. Nicky Romero) - Radio Edit"
songs$Artist[songs$Artist == "Axwell Λ Ingrosso" |
             songs$Artist == "Axwell / Ingrosso"] = "Axwell /\ Ingrosso"
songs$Track[songs$Track == "The Way I Are (Dance with Somebody) [feat. Lil Wayne]"] = "The Way I Are (Dance with Somebody)"
songs$Track[songs$Track == "Heaven Is A Place On Earth - 2009 Digital Remaster"] = "Heaven Is A Place on Earth"
songs$Artist[songs$Artist == "Beyoncé"] = "Beyonce"
songs$Track[songs$Track == "Mony Mony - Downtown Mix / 24-Bit Digitally Remastered 2001"] = "Mony Mony - 24-Bit Digitally Remastered 01"
songs$Track[songs$Track == "Call Me - Digitally Remastered 98"] = "Call Me"
songs$Artist[songs$Artist == "Bobby 'Boris' Pickett"] = "Bobby Boris Pickett & The Crypt-Kickers"
songs$Track[songs$Track == "Rockin' Around The Christmas Tree - Single Version"] = "Rockin' Around The Christmas Tree"
songs$Track[songs$Track == "All This Time - Pop Mix"] = "All This Time"
songs$Track[songs$Track == "Be The Change - Radio Version"] = "Be the Change"
songs$Track[songs$Track == "Gold (Jason Nevins Rhythmic Radio) Remix"] = "Gold - Jason Nevins Rhythmic Remix/Bonus Track"
songs$Track[songs$Track == "Ready or Not - feat. Lecrae"] = "Ready or Not"
songs$Track[songs$Track == "Santa Claus Is Comin' to Town - C.W. Post College Greenvale NY - December 1975"] = "Santa Claus Is Comin' To Town - Single Version"
songs$Track[songs$Track == "A Holly Jolly Christmas - Single Version"] = "A Holly Jolly Christmas"
songs$Artist[songs$Artist == "Céline Dion"] = "Celine Dion"
songs$Track[songs$Track == "Ashes - from the Deadpool 2 Motion Picture Soundtrack" |
            songs$Track == "Ashes - from Deadpool 2 Motion Picture Soundtrack"] = "Ashes - from Deadpool 2"
songs$Track[songs$Track == "Because You Loved Me (Theme from Up Close and Personal)"] = "Because You Loved Me"
songs$Track[songs$Track == "My Heart Will Go On - Love Theme From Titanic"] = "My Heart Will Go On"
songs$Track[songs$Track == "I Need Your Love (feat. Ellie Goulding)"] = "I Need Your Love"
songs$Track[songs$Track == "Outside (feat. Ellie Goulding)"] = "Outside"
songs$Track[songs$Track == "E•MO•TION"] = "Emotion"
songs$Track[songs$Track == "I Didn’t Just Come Here To Dance"] = "I Didn't Just Come Here To Dance"
songs$Track[songs$Track == "Let’s Get Lost"] = "Let's Get Lost"
songs$Track[songs$Track == "Tonight I’m Getting Over You"] = "Tonight I'm Getting Over You"
songs$Track[songs$Track == "Tonight I’m Getting Over You - Reid Stefan Remix"] = "Tonight I'm Getting Over You - Reid Stefan Remix"
songs$Track[songs$Track == "Tonight I’m Getting Over You - Remix"] = "Tonight I'm Getting Over You - Remix"
songs$Artist[songs$Artist == "Carly Rae Jepsen | www.soundfox.co"] = "Carly Rae Jepsen"
songs$Track[songs$Track == "Circle Of Life - From The Lion King/Soundtrack" |
            songs$Track == "Circle of Life"] = "Circle of Life - From The Lion King"
songs$Track[songs$Track == "Ever Ever After - From Enchanted / Soundtrack Version"] = "Ever Ever After - Soundtrack"
songs$Track[songs$Track == "Make Your Own Kind Of Music - Remastered - Single Version"] = "Make Your Own Kind of Music"
songs$Track[songs$Track == "Sex (Cheat Codes X Kris Kross Amsterdam)"] = "Sex"
songs$Track[songs$Track == "Reflection - From Mulan / Pop Version" |
            songs$Track == "Reflection - Pop Version"] = "Reflection"
songs$Track[songs$Track == "We Remain - From “The Hunger Games: Catching Fire”/ Soundtrack"] = "We Remain - From 'The Hunger Games: Catching Fire' Soundtrack"
songs$Track[songs$Track == "Can’t Help Falling In Love - The Voice Performance"] = "Can't Help Falling In Love - The Voice Performance"
songs$Track[songs$Track == "Hold On We’re Going Home - The Voice Performance"] = "Hold On We're Going Home - The Voice Performance"
songs$Track[songs$Track == "I Won’t Give Up - The Voice Performance"] = "I Won't Give Up"
songs$Track[songs$Track == "When You Wish Upon a Star - From Pinocchio"] = "When You Wish Upon a Star"
songs$Track[songs$Track == "Dream Ghost (feat. Michael Hyatt Amber Riley & Ricki Lake)"] = "Dream Ghost"
songs$Track[songs$Track == "Greg’s Drinking Song"] = "Greg's Drinking Song"
songs$Track[songs$Track == "I’m A Good Person" |
            songs$Track == "I'm a Good Person (feat. Rachel Bloom)"] = "I'm A Good Person"
songs$Artist[songs$Artist == "Верка Сердючка"] = "Verka Serduchka"
songs$Track[songs$Track == "	Hey Mama (feat. Nicki Minaj & Afrojack)"] = "Hey Mama (feat. Nicki Minaj Bebe Rexha & Afrojack)"
songs$Track[songs$Track == "Titanium"] = "Titanium (feat. Sia)"
songs$Track[songs$Track == "When Love Takes Over (feat. Kelly Rowland) - feat. Kelly Rowland"] = "When Love Takes Over (feat. Kelly Rowland)"
songs$Track[songs$Track == "Where Them Girls At - feat. Nicki Minaj & Flo Rida"] = "Where Them Girls At (feat. Nicki Minaj & Flo Rida)"
songs$Track[songs$Track == "Pour Some Sugar On Me - Remastered 2017"] = "You Spin Me Round (Like a Record)"
songs$Track[songs$Track == "Listen To Your Heart (Edmée's Unplugged Vocal)"] = "Listen To Your Heart (Edmee's Unplugged Vocal)"
songs$Track[songs$Track == "Cake By The Ocean - クリーン・ヴァージョン"] = "Cake by The Ocean"
songs$Track[songs$Track == "Stereo Love Featuring Vika Jigulina - Radio Edit"] = "Stereo Love - Radio Edit"
songs$Track[songs$Track == "Hanging On - Edit"] = "Hanging On"
songs$Track[songs$Track == "Still Falling For You - From Bridget Jones's Baby Original Motion Picture Soundtrack"] = "Still Falling For You - From Bridget Jones's Baby"
songs$Track[songs$Track == "Can You Feel The Love Tonight - End Title / From The Lion King"] = "Can You Feel the Love Tonight"
songs$Track[songs$Track == "When I’m Alone"] = "When I'm Alone"
songs$Track[songs$Track == "There You'll Be - Remastered Version"] = "There You'll Be - Remastered"
songs$Track[songs$Track == "Work from Home (feat. Ty Dolla $ign)"] = "Work From Home"
songs$Track[songs$Track == "100 Years: Music Video"] = "100 Years"
songs$Track[songs$Track == "Right Round - US"] = "Right Round"
songs$Track[songs$Track == "Say It"] = "Say It (feat. Tove Lo)"
songs$Track[songs$Track == "We Are Young (feat. Janelle Monáe) - feat. Janelle Monae" |
            songs$Track == "We Are Young (feat. Janelle Monáe)"] = "We Are Young (feat. Janelle Monae)"
songs$Track[songs$Track == "Saving Light"] = "Saving Light (feat. Haliene)"
songs$Track[songs$Track == "Feel Good (feat. Daya)"] = "Feel Good"
songs$Track[songs$Track == "I Got Nerve - From Hannah Montana/Soundtrack Version"] = "I Got Nerve"
songs$Track[songs$Track == "Nobody's Perfect - From Hannah Montana 2"] = "Nobody's Perfect"
songs$Track[songs$Track == "The Best of Both Worlds - From Hannah Montana/Soundtrack Version"] = "The Best of Both Worlds"
songs$Track[songs$Track == "The Other Side of Me - From Hannah Montana/Soundtrack Version"] = "The Other Side of Me"
songs$Track[songs$Track == "Christ Is Enough - Live"] = "Christ Is Enough"
songs$Artist[songs$Artist == "Hixxy"] = "Gareth Emery"
songs$Track[songs$Track == "Saving Light (Hixxy Remix) [feat. HALIENE]"] = "Saving Light - Hixxy Remix"
songs$Track[songs$Track == "Black Widow (feat. Rita Ora) - Clean Edit"] = "Black Widow"
songs$Artist[songs$Artist == "Jason Derülo"] = "Jason Derulo"
songs$Track[songs$Track == "Flashlight - From Pitch Perfect 2 Soundtrack"] = "Flashlight - From Pitch Perfect 2"
songs$Track[songs$Track == "Part Of Your World - From The Little Mermaid/ Soundtrack Version"] = "Part of Your World - From The Little Mermaid / Soundtrack Version"
songs$Track[songs$Track == "Happy Xmas (War Is Over) - Remastered"] = "Happy Xmas (War Is Over) - 2010 Digital Remaster"
songs$Artist[songs$Artist == "John Martyn"] = "John Martin"
songs$Track[songs$Track == "St. Elmos Fire [Man In Motion]"] = "St. Elmo's Fire (Man in Motion)"
songs$Track[songs$Track == "It's Beginning To Look Like Christmas"] = "It's Beginning to Look a Lot Like Christmas"
songs$Track[songs$Track == "Too Little Too Late - Radio Version"] = "Too Little Too Late"
songs$Artist[songs$Artist == "José Feliciano"] = "Jose Feliciano"
songs$Track[songs$Track == "Can You Feel The Love Tonight - From The Lion King/Soundtrack Version"] = "Can You Feel the Love Tonight"
songs$Track[songs$Track == "Angels We Have Heard On High (with Brian McKnight)"] = "Angels We Have Heard On High - Duet With Brian Mcknight"
songs$Track[songs$Track == "O Come All Ye Faithful (With The Mormon Tabernacle Choir under the direction of Craig Jessop) - with The Mormon Tabernacle Choir under the direction of Craig Jessop Album Version" | 
            songs$Track == "O Come All Ye Faithful - with The Mormon Tabernacle Choir under the direction of Craig Jessop"] = "O Come All Ye Faithful (with The Mormon Tabernacle Choir under the direction of Craig Jessop)"
songs$Track[songs$Track == "The First Noël - duet with Faith Hill" | 
            songs$Track == "The First Noël (with Faith Hill) - duet with Faith Hill Album Version"] = "The First Noel - Duet With Faith Hill"
songs$Track[songs$Track == "California Gurls - feat. Snoop Dogg"] = "California Gurls (feat. Snoop Dogg)"
songs$Track[songs$Track == "Dark Horse (feat. Juicy J)"] = "Dark Horse"
songs$Track[songs$Track == "E.T. - feat. Kanye West"] = "	E.T."
songs$Track[songs$Track == "Heartbeat Song - Dave Audé Radio Mix"] = "Heartbeat Song - Dave Aude Radio Mix"
songs$Track[songs$Track == "Carry Me (feat. Julia Michaels)"] = "Carry Me"
songs$Track[songs$Track == "It Ain’t Me (with Selena Gomez)"] = "It Ain't Me"
songs$Track[songs$Track == "Scheiße"] = "Scheibe"
songs$Track[songs$Track == "Shallow - Radio Edit"] = "Shallow"
songs$Track[songs$Track == "Telephone (feat. Beyoncé)"] = "Telephone (feat. Beyonce)"
songs$Track[songs$Track == "Yoü and I"] = "You and I"
songs$Track[songs$Track == "Summertime Sadness (Lana Del Rey Vs. Cedric Gervais) - Cedric Gervais Remix" |
            songs$Track == "Summertime Sadness [Lana Del Rey vs. Cedric Gervais] - Cedric Gervais Remix"] = "Summertime Sadness (Lana Del Rey Vs. Cedric Gervais) - Cedric Gervais Remix / Radio Edit"
songs$Track[songs$Track == "A Whole New World - From Aladdin/ Soundtrack Version"] = "A Whole New World"
songs$Track[songs$Track == "God Bless The U.S.A. - Re-Recorded In Stereo" |
            songs$Track == "God Bless The U.S.A."] = "God Bless the USA"
songs$Track[songs$Track == "Longer Than I Thought (feat. Joe Jonas)"] = "Longer Than I Thought"
songs$Track[songs$Track == "Too Far Gone (feat. Anna Clendening)"] = "Too Far Gone"
songs$Track[songs$Track == "Dominick the Donkey (The Italian Christmas Donkey)"] = "Dominick The Italian Christmas Donkey"
songs$Track[songs$Track == "What A Wonderful World - Single Version"] = "What a Wonderful World"
songs$Track[songs$Track == "Bad Things - With Camila Cabello"] = "Bad Things"
songs$Track[songs$Track == "I Won't Let You Walk Away (feat. Madison Beer) - Lost Kings Remix"] = "I Won't Let You Walk Away - Lost Kings Remix"
songs$Track[songs$Track == "I Won't Let You Walk Away (feat. Madison Beer) - Radio Edit" |
            songs$Track == "I Won't Let You Walk Away (feat. Madison Beer) - Pop Radio Edit"] = "I Won't Let You Walk Away - Radio Edit"
songs$Artist[songs$Artist == "Marina"] = "Marina & the Diamonds"
songs$Track[songs$Track == "She Will Be Loved - Radio Mix"] = "She Will Be Loved"
songs$Artist[songs$Artist == "MGM Studio Orchestra"] = "MGM Studio Chorus"
songs$Artist[songs$Artist == "Molly Sandén"] = "Molly Sanden"
songs$Track[songs$Track == "O Tannenbaum - Remastered 1999"] = "O Tannenbaum"
songs$Track[songs$Track == "Hakuna Matata - From The Lion King/Soundtrack"] = "Hakuna Matata"
songs$Artist[songs$Artist == "Owl City & Carly Rae Jepsen"] = "owl City"
songs$Track[songs$Track == "You’re Not Alone"] = "You're Not Alone"
songs$Track[songs$Track == "Can We Pretend (feat. Cash Cash)"] = "Can We Pretend"
songs$Track[songs$Track == "There’s A Honey"] = "There's A Honey"
songs$Track[songs$Track == "Hit Me With Your Best Shot - 1999 Digital Remaster"] = "Hit Me With Your Best Shot"
songs$Track[songs$Track == "You'll Be In My Heart (Phil Version) - 『ターザン』より" |
            songs$Track == "You'll Be In My Heart - From Tarzan/Soundtrack Version" |
            songs$Track == "You Will Be In My Heart"] = "You'll Be In My Heart"
songs$Track[songs$Track == "Qué Sera Sera"] = "Que Sera Sera"
songs$Artist[songs$Artist == "Raven-Symoné"] = "Raven-Symone"
songs$Track[songs$Track == "We Found Love (Album Version) [Feat. Calvin Harris]"] = "We Found Love (feat. Calvin Harris)"
songs$Track[songs$Track == "Go the Distance - 『ヘラクレス』より" |
            songs$Track == "Go the Distance - From Hercules / Soundtrack Version" |
            songs$Track == "Go The Distance - From Hercules/Soundtrack"] = "Go The Distance"
songs$Track[songs$Track == "Under the Sea - From The Little Mermaid / Soundtrack Version" |
            songs$Track == "Under the Sea - From The Little Mermaid"] = "Under The Sea - From The Little Mermaid/ Soundtrack Version"
songs$Track[songs$Track == "When She Loved Me - From Toy Story 2/Soundtrack Version" |
            songs$Track == "When She Loved Me - From Toy Story 2"] = "When She Loved Me"
songs$Track[songs$Track == "Back To You - From 13 Reasons Why – Season 2 Soundtrack"] = "Back To You"
songs$Track[songs$Track == "Don’t Leave"] = "Don't Leave"
songs$Track[songs$Track == "First Time (feat. Dylan Matthew)"] = "First Time"
songs$Track[songs$Track == "Easy Love - Original Mix"] = "Easy Love"
songs$Track[songs$Track == "Sweet Lovin' - Original Mix" |
            songs$Track == "Sweet Lovin' - Radio Edit"] = "Sweet Lovin'"
songs$Track[songs$Track == "All My Friends (feat. Tinashe & Chance The Rapper)"] = "All My Friends"
songs$Track[songs$Track == "Live Love Learn (feat. Peg Parnevik)"] = "Live Love Learn"
songs$Track[songs$Track == "Wannabe - Radio Edit"] = "Wannabe"
songs$Track[songs$Track == "I Won't Say (I'm In Love) - 『ヘラクレス』より" |
            songs$Track == "I Won't Say (I'm In Love) - From Hercules"] = "	I Won't Say (I'm In Love)"
songs$Track[songs$Track == "Don't You Worry Child (Radio Edit) [feat. John Martin]" |
            songs$Track == "Don't You Worry Child (Radio Edit)"] = "Don't You Worry Child - Radio Edit"
songs$Track[songs$Track == "...Ready for It?"] = "... Ready For It?"
songs$Track[songs$Track == "Bellas Finals: Price Tag/Don’t You (Forget About Me)/Give Me Everything/Just The Way You Are/Party In The U.S.A./Turn The Beat Around"] = "Bellas Finals: Price Tag/Don't You (Forget About Me)/Give Me Everything/Just The Way You Are/Party In The U.S.A./Turn The Beat Around"
songs$Track[songs$Track == "Cups (“When I’m Gone”) - Campfire Version"] = "Cups ('When I'm Gone') - Campfire Version"
songs$Track[songs$Track == "Riff Off: Mickey/Like A Virgin/Hit Me With Your Best Shot/S&M/Let’s Talk About Sex/I’ll Make Love To You/Feels Like The First Time/No Diggity"] = "Riff Off: Mickey/Like A Virgin/Hit Me With Your Best Shot/S&M/Let's Talk About Sex/I'll Make Love To You/Feels Like The First Time/No Diggity"
songs$Track[songs$Track == "Do You Mean (with Ty Dolla $ign & bülow)"] = "Do You Mean"
songs$Track[songs$Track == "Side Effects (feat. Emily Warren)"] = "Side Effects"
songs$Track[songs$Track == "Takeaway"] = "Takeaway (with ILLENIUM & Lennon Stella)"
songs$Track[songs$Track == "Our Lips Are Sealed - Single Version"] = "Our Lips Are Sealed"
songs$Track[songs$Track == "We Got The Beat - Single Mix"] = "We Got the Beat"
songs$Artist[songs$Artist == "Tiësto"] = "Tiesto"
songs$Track[songs$Track == "I’m Me"] = "I'm Me"
songs$Track[songs$Track == "Another Shot‬‬‬"] = "Another Shot"
songs$Track[songs$Track == "We’re The Same"] = "We're the Same"
songs$Track[songs$Track == "	I Have Nothing - Remastered"] = "I Have Nothing"
songs$Track[songs$Track == "The Star Spangled Banner (feat. The Florida Orchestra) - Live from Super Bowl XXV"] = "The Star Spangled Banner - Live from Super Bowl XXV"
songs$Track[songs$Track == "Clarity - feat. Foxes"] = "Clarity"
songs$Track[songs$Track == "Happy Now (with Elley Duhé)"] = "Happy Now"
songs$Track[songs$Track == "I Want You to Know (feat. Selena Gomez)"] = "I Want You to Know"

distincts = songs %>% 
  group_by(Artist,Track) %>%
  summarize(streams = n())

qualifying = distincts %>% filter(streams >= 5)

qsongs = songs %>% inner_join(.,qualifying,by=c("Artist","Track")) %>% select(-c(streams))
```










